name = input("enter your name :")
course = input("entrer youe course :")
cr1 = int(input("Enter first credit :"))
c1 = int(input("Enter first cpi :"))
cr2 = int(input("Enter second credit :"))
c2 = int(input("Enter second cpi :"))
cr3 = int(input("Enter third credit :"))
c3 = int(input("Enter third cpi :"))
spi = (cr1*c1 + cr2*c2 + cr3*c3) / (cr1+cr2+cr3)


print("your name:", name)
print("cr1 : ", cr1)
print("c1 : ", c1)
print("cr2 : ", cr2)
print("c2 : ", c2)
print("cr3 : ", cr3)
print("c3 : ", c3)
print(spi)
